---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chartinstalls.helm-repository.openshift.io
spec:
  group: helm-repository.openshift.io
  names:
    kind: ChartInstall
    listKind: ChartInstallList
    plural: chartinstalls
    singular: chartinstall
  scope: Namespaced
  versions:
   - additionalPrinterColumns:
     name: v1alpha1
     schema:
       openAPIV3Schema:
         description: 'ChartInstall is an installation request for a Helm Chart.'
         type: object
         properties:
           apiVersion:
             description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
             type: string
           kind:
             description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
             type: string
           metadata:
             type: object
           spec:
             description: 'ChartInstallSpec defines the request parameters (values) for installation of a Helm Chart'
             type: object
             required:
             - values
             - chart
             properties:
               values:
                 description: "Array of helm chart parameters overriding the chart's defaults in the values.yaml."
                 type: array
                 items:
                   description: "Every item represents a single parameter."
                   type: object
                   properties:
                     name:
                       description: "Parameter name"
                       type: string
                     value:
                       # Think about extending that to an object (map)
                       x-kubernetes-int-or-string: true
                       anyOf:
                       - type: integer
                       - type: string
               chart:
                 description: 'Copy of a HelmChart resource to be installed.'
                 type: object
                 properties:
### Start of part shared with HelmChart CRD
                   apiVersion:
                     description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                     type: string
                   kind:
                     description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                     type: string
                   metadata:
                     type: object
                   spec:
                     description: 'ChartSpec defines the desired content of Helm Chart'
                     type: object
                     required:
                     - templates
                     - values 
                     properties:
                       templates:
                         description: 'Array of temaplate base64-encoded yaml files'
                         type: array
                         items:
                           description: 'A template represents base64-encoded content of a single Helm Chart template .yaml file.'
                           type: object
                           properties:
                             name:
                               description: 'Template file name'
                               type: string
                             b64Content:
                               description: 'Encoded file content'
                               type: string
                       values:
                         description: 'Helm default values, base64 encoded.'
                         type: string
                       description:
                         description: "For Chart.yaml"
                         type: string
                       version:
                         description: "For Chart.yaml"
                         type: string
                       appVersion:
                         description: "For Chart.yaml"
                         type: string
                       license:
                         desciption: "Base64 encoded chart's licence. Expected to be set when the chart is exposed publicly."
                         type: string
                       readme:
                         desciption: "Base64 encoded chart's README file. Expected to be set when the chart is exposed publicly."
                         type: string
### End of part shared with HelmChart CRD
     served: true
     storage: true
     subresources:
       status: {}
status:
  conditions: []
  storedVersions: []

