---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chartinstalls.helm-repository.openshift.io
spec:
  group: helm-repository.openshift.io
  names:
    kind: ChartInstall
    listKind: ChartInstallList
    plural: chartinstalls
    singular: chartinstall
  scope: Namespaced
  versions:
   - additionalPrinterColumns:
     name: v1alpha1
     schema:
       openAPIV3Schema:
         description: 'ChartInstall is an installation request for a Helm Chart.'
         type: object
         properties:
           apiVersion:
             description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
             type: string
           kind:
             description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
             type: string
           metadata:
             type: object
           spec:
             description: 'ChartInstallSpec defines the request parameters (values) for installation of a Helm Chart'
             type: object
             required:
             - chartRef
             - values
             properties:
               values:
                 description: "Array of helm chart parameters overriding the chart's defaults in the values.yaml."
                 type: array
                 items:
                   description: "Every item represents a single parameter."
                   type: object
                   properties:
                     name:
                       description: "Parameter name"
                       type: string
                     value:
                       # Think about extending that to an object (map)
                       x-kubernetes-int-or-string: true
                       anyOf:
                       - type: integer
                       - type: string
               chartRef:
                 description: 'Reference to a chart to be installed.'
                 type: object
                 properties:
                   name:
                     description: 'HelmChart name (reference)'
                     type: string
                   namespace:
                     description: 'HelmChart namespace (reference)'
                     type: string
     served: true
     storage: true
     subresources:
       status: {}
status:
  conditions: []
  storedVersions: []

